yuzu-emu/yuzu-emu.github.io

site/layouts/partials/homepage/heroContents.html
src/scss/shared.scss

Depends on https://github.com/chris062689/shared-bulma-theme/pull/7

Clean up jumbotron labels, update to latest shared theme

---

site/content/entry/yuzu-progress-report-2018-p1-2/index.md

Insta merge please :man_facepalming:
cc: @bunnei

Fix PR typo

---

site/layouts/page/downloads.html

This updates the description of the current state of yuzu in the downloads page, ~~stopping redditors complaining~~.

Fix current state of yuzu in downloads page

---

src/scss/shared.scss

Depends on https://github.com/chris062689/shared-bulma-theme/pull/13

Import img shortcode from shared theme

---

site/content/help/features/modding.md
site/content/help/quickstart/quickstart.md
site/content/help/reference/errors.md

Includes new key-derivation quickstart guide, basic errors & troubleshooting guide, and modding guide.

Add new guides

---

site/content/help/quickstart/console.keys
site/content/help/quickstart/quickstart.md
site/content/help/quickstart/yuzu_copy.bat

Using data from the Saturday beta test

Update guide with beta test fixes

---

site/content/help/quickstart/yuzu_copy.bat

Tidied up a few errors. Updated yuzu_copy.bat, left the original script alone, but edited in away for the .bat to check if the backup has a nand ID or not.

Fixed a few errors: Updated yuzu_copy.bat to account for nand ID

---

site/layouts/page/downloads.html
site/layouts/partials/homepage/heroContents.html

* Removed references in homepage and download page.
* Added a note in the Downloads page for macOS.
* also edited wiki pages to reflect these changes.
cc: @chris062689

Removed refs to macOS

---

site/content/help/quickstart/yuzu_copy.bat

Added notifications concerning `rawnand.bin` as to whether or not it is one file, where the combined files were combined, and letting the user know to continue with quickstart guide.

Added notifications concerning rawnand.bin

---

site/content/help/feature/boxcat/index.md

Just fixed some grammar to make it sound and look better.

Boxcat: Fix grammar

---

site/data/bounties.json

Remove 'implement internal resolution scaling.' bounty

---

site/content/help/quickstart/index.md

Edit grammar and add IDs to sections

---

site/content/help/reference/log-files.md

This PR is a part 1 of my ongoing log file guide overhaul. Part 2 will overhaul Citra's logging guide on the community forums. Design suggestions / changes are welcome, same with grammar point-outs.
Special thanks to @jroweboy for informing me how the logging system works on Linux.

Log file gathering guide implementation

---

site/content/help/reference/log-files.md

Log file guide fixup: post it back -> upload

---

site/content/help/quickstart/index.md
site/content/help/reference/log-files.md

* fixed `log-files` page bullet lists.
* added sample image in `log-files`.
* added `hardware` anchor in `quickstart` guide. (required for yuzubot)

Minor Changes

---

site/content/entry/yuzu-migration/index.md

Merging - after testing on the staging site.

Fix post timestamp

---

site/layouts/page/downloads.html

Reverts yuzu-emu/yuzu-emu.github.io#156

Revert "Update download.html for yuzu_install.exe 1.8"

---

site/content/help/feature/game-modding.md

Fixed indentation and more

---

site/content/help/quickstart/index.md

Also corrects a small oversight in step 2e pointing to 1d instead of 2d

Update Quickstart Guide video link

---

.gitmodules

Migrated submodules to those under yuzu-emu org

Migrate submodules

---

site/content/entry/yuzu-prometheus/index.md

Would rather have the video at the top to show off the performance changes than at the bottom where no one will see it.

Move the video to the top of the page

---

site/config.toml

Removed help page in favor of faq page, added profile page for patrons to link their accounts

updating navbar for faq changes

---

site/content/help/quickstart/index.md

To better reflect multicore, and added a laptop disclaimer.

Changes to specs

---

gulpfile.js
package.json
yarn.lock

This Pull Request fixes the thumbnail generation and updates the NPM dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yuzu-emu/yuzu-emu.github.io/189)

Fix thumbnail generation

---

site/content/entry/yuzu-progress-report-jul-2020/index.md

Amend CPU model

---

site/content/entry/yuzu-progress-report-aug-2020/index.md

(even though I'm not the author, and only edited the article)

Fixed author name

---

src/scss/yuzu/yuzu.scss

This _should_ fix the button color.

Fix manual download button color

---

site/content/entry/yuzu-nvdec-emulation/index.md

Codec naming changes

---

.github/workflows/deploy.yml

This Pull Request fixes the wiki URL (taken from the Travis CI settings), and the wiki contents should be correct now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yuzu-emu/yuzu-emu.github.io/211)

ci: fix wiki url

---

site/content/help/quickstart/index.md

changing links to point to the download pages instead of outdated nros

Update links to NRO links

---

.github/workflows/deploy.yml

* Schedule daily build at 00:00 UTC
* Based on the following reference:
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events

Add cron schedule for daily build

---

site/content/help/quickstart/index.md

update to reflect all recent releases of atmosphere, not just the stable releases, as the latest stable release doesn't have support for 11.0.x, which a few users have needed help with lately.

Update index.md to get the latest atmosphere release

---

site/config.toml

Point "Blog" to yuzu-emu.org/entry

---

gulpfile.js
package.json
src/scss/style.scss
yarn.lock

Update the submodules and `gulpfile` to fix several issues. The changes could be seen from the `yuzu-emu/shared-hugo-theme` repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yuzu-emu/yuzu-emu.github.io/248)

Update submodules and build script

---

package.json
yarn.lock

Update the submodules to fix several issues. The changes could be seen from the `yuzu-emu/shared-hugo-theme` repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yuzu-emu/yuzu-emu.github.io/264)

Update submodules and dependencies

---

site/layouts/partials/layout/sidebar.html
src/scss/yuzu/yuzu.scss

- CSS changes made to font size and line height
-  replace old sidebar ad column with a horizontal column and repositioned it to the bottom
- pull layout and misc changes from submodule.

Minor changes to improve content readability

---

.gitignore
maintenance.html

Add maintenance page

---

site/content/entry/yuzu-progress-report-jan-2022/index.md

As requested by dev, updated the description of the change mentioned in the report.

Update description of theme changes

---

site/content/downloads.md

The most common graphical issues support requests are related to this

Download: Suggest Intel and AMD Windows users to use Vulkan

---

site/assets/scss/shared.scss

https://github.com/yuzu-emu/shared-bulma-theme/pull/13 should be merged first.

scss\shared: Add css definitions for game list search and pagination

---

site/data/bounties.json

All of them have been fixed years ago.

bounties: Move all bounties to completed status
