yuzu-emu/yuzu-emu.github.io

site/config.toml

This adds a Patreon link to the navbar.
Decision was made to leave current donation page as-is for now.

Add Patreon link

---

site/content/donate.md

This corrects a note left in the donations page erroneously saying there is no Patreon available.

Correct donations page

---

src/scss/yuzu/yuzu.scss

This fixes a previously introduced bug where styling was incorrectly applied to blocks of code (wrapped in `<pre>` tags).
Fixed styling (rest of document has broken markup, but not due to this PR):

Fix backgrounds of pre-wrapped code

---

site/layouts/page/downloads.html
src/scss/yuzu/yuzu.scss

This publishes the new installer to the website, as well as providing infrastructure for handling other devices.
From a Windows device:
From a device with Javascript disabled:
View is the same as it was previously for Mac/Linux (until Flatpak is ready).

Add Windows/no-script specific download views

---

site/layouts/partials/homepage/heroContents.html

When the download button in the middle of the homepage is clicked, a new tab won't be opened now.
This behavior pissed me off so hard, that I had to make a PR for it :P

Don't open a new tab when the download button is clicked (Take 2)

---

site/content/help/quickstart/index.md

Pointing the Hekate and Biskey dump to the webpages where the versions are hosted instead of linking to static downloads.

Updated the quickstart links

---

site/content/help/quickstart/console.keys

The latest BISKey dump combines both crypt and tweak into one line. Changes clarify which key is which and if the last BIS Key, 3, is needed to be copied as well.

Adding info concerning key length

---

site/content/downloads.md

Canary is now the recommended build. Change the download blurb / guide to account for that.

Switch Nightly -> Canary as the recommended build in the download section

---

site/content/help/quickstart/index.md

This pull request aims to make the quickstart guide more in line with the new Lockpick update.
Because of this new update, prod.keys and title.keys dumping has been made significantly easier.

Update the quickstart guide

---

site/layouts/page/downloads.html

Users have reported that the "view package listing" button is confusing
Renaming the button to "Manual Download" to mirror Citra

Rename package listing button

---

src/js/downloads.js

Multiple users have brought up the fact that it's confusing when trying to manually download a Windows release because there are 3 or 4 available. Updated the download script to reject any windows builds besides the standard .zip release.

Only show .zip windows release

---

site/content/help/quickstart/index.md

Old ones had OEM CPUs listed, old GPUs, and didn't contemplate Zen2.
I'm open on the opinion of recommending a 1060 6GB, it should be enough for avoiding GPU bottlenecks, and the extra VRAM will be needed in "future updates".

Minor changes on minimum requirements

---

site/content/entry/yuzu-prometheus/index.md

Fixed one of the links for Blinkhawk's github, which was linking to dynarmic instead.

Fixed Bad Link

---

.travis.yml
gulpfile.js
package.json
src/scss/style.scss
yarn.lock

This PR will add a mechanism to generate thumbnails for the images in the news posts.
For the record, there was a discussion that the news page will cause the viewer to generate a huge amount of network traffic due to too many high-resolution images are loaded by default.
This PR will __only__ add the thumbnail generation, and a future PR will be opened for actually making use of those thumbnails in [a different repository](https://github.com/yuzu-emu/shared-bulma-theme).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yuzu-emu/yuzu-emu.github.io/183)

Generate Thumbnails for Images

---

site/content/help/feature/resolution-rescaler/index.md

Adds:
> **PSA:** Due to some stability issues and not working on other GPU vendors (Intel/AMD), the feature has been removed and is currently absent in the latest Mainline/Early Access builds. Resolution scaling will return at a later date once the aforementioned issues are fixed by the development team.

Add a PSA addressing the current state of the Resolution scaling feature

---

site/content/help/quickstart/index.md

Marked the following sections as Optional since they're not essentially required for initial emulation functionality anymore:
- Dumping BIS Keys (Optional)
- Backing up System Files (Optional but Recommended)
- Moving SYSTEM and USER to the yuzu directory (Optional)

Update Quickstart Guide sections

---

.github/workflows/deploy.yml

This Pull Request will migrate CI to GitHub Actions.
Since it's provided by GitHub, no setup is required. Just need to shut down the old CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yuzu-emu/yuzu-emu.github.io/209)

Migrate to GitHub Actions

---

src/scss/yuzu/yuzu.scss

Updates the `<code>` tag style as inspired by other modern styles.
Before:
After:

Update <code> tag style

---

src/scss/yuzu/yuzu.scss

This PR overwrites a few bulma CSS properties that were changed when we upgraded from `0.7.2` to `0.9.0` in https://github.com/yuzu-emu/yuzu-emu.github.io/pull/183
These changes allow for the Switch SVG to scale properly and the image overlay to be aligned with it.
Thanks to @Schplee for digging through the CSS changes. 
Tested changes locally but for some reason, netlify render doesn't work.

fix svg scaling and overlay alignment

---

site/content/downloads.md

Removes the dependencies list from the Linux section, since the downloads page no longer links to the prebuilt binaries and now instead to the AppImage. Adds instructions on how to run the AppImage.

downloads: AppImage instructions in Linux section

---

src/scss/yuzu/yuzu.scss

Updates the style of multi-line code blocks to be more consistent with the website theme and modern styles of the `pre` preformatted text blocks.
Before:
After:
Closes #238

Update style of multi-line code blocks

---

src/js/downloads.js

Prevents the site from showing both AppImage and AppImage.zsync files for Linux.

downloads: Don't include .zsync files

---

src/scss/yuzu/yuzu.scss

This fixes the issue of anchor links jumping too far due to the fixed header. 
* The solution was taken from <https://stackoverflow.com/a/28824157>
* Tested on Chrome 87 and Firefox 84
---
For creating anchor links, use Hugo in-built shortcodes `ref` or `relref`. For more details, see [here](https://gohugo.io/content-management/cross-references/) & [here](https://bwaycer.github.io/hugo_tutorial.hugo/extras/crossreferences/)
Fixes #239

fix anchor jump issue

---

site/content/help/quickstart/index.md

Replaces the use of the [Goldleaf](https://github.com/XorTroll/Goldleaf) homebrew application with the [TegraExplorer](https://github.com/suchmememanyskill/TegraExplorer) tool RCM payload for dumping the system update firmware. The steps for dumping the firmware are also updated in correspondence to the new tool.
As of now, the latest stable release of Goldleaf is not yet compatible on Switch firmware 11.x.x, with no confirmed release window for an update. We had to redirect users to a beta build from a temporary link different from the one in the Quickstart Guide as a temporary solution. This Pull Request resolves that by replacing Goldleaf with TegraExplorer. TegraExplorer is a suitable alternative tool for dumping the system firmware and it's compatibility is not affected by system …

Replace Goldleaf with TegraExplorer for system update firmware dumping

---

site/content/entry/yuzu-progress-report-jan-2021/index.md

There was an error in the description of cases that yield NaN values. The erroneous data was scrapped.

Fix innacuracy about NaN values.

---

site/content/help/quickstart/index.md

Thanks to AMD killing older GCN cards with the release of FSR, we need to separate hardware recommendations between Windows and Linux, plus provide better explanations and examples regarding CPU, GPU and RAM requirements.
Nod to iGPU users that aren't able to get a dGPU in the current market.

Major changes to hardware requirements

---

site/content/help/quickstart/index.md

Changes in this PR:
- Starting from Atmosphere 1.0.0, it's bootloader was re-written and the filename for its payload has been changed from `fusee-primary.bin` to `fusee.bin`.
- Some steps are updated to adapt on changes made from the latest Lockpick_RCM and TegraExplorer releases.
- Steps for save dumping have been significantly changed to replace the use of Checkpoint in favor of JKSV, as the latter is able to dump save data from many other sources (Device, BCAT, etc.) and compatible with recent Switch firmware versions.

Update Quickstart Guide

---

gulpfile.js
package.json
site/config.toml
site/content/entry/yuzu-progress-report-jan-2022/index.md
site/layouts/shortcodes/gh-hovercard.html
src/js/github.js
yarn.lock

This pull request adds a GitHub-style hovercard implementation.
Usage:
```html
{{< gh-hovercard "7624" "rendering directly into the scaled image" >}}
{{< gh-hovercard-include-end >}}
```

shortcodes: add GitHub style hovercards

---

site/assets/scss/yuzu/yuzu.scss
site/content/downloads.md
site/layouts/page/downloads.html

- Removes extra click for builds
- Moves download to very top, and on larger screens, moves it to the right
- Uses tabs for the info dump to let people get to builds faster
- Tidies up some scripts
- Shows links for both if platform is unsupported or js is diabled.

Download Page Rework

---

site/content/help/reference/asking.md

Noticed this was incorrectly copied from the Citra website as I was going over that to edit it.
The #welcome channel doesn't actually exist in the server, so best to edit it with the name for the first channel users are presented with when joining the server for the first time.

Edit Discord server instructions to the correct channel name.
